### ISSUE TITLE
Add `CallbackVars` to flagSet

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/goflags#103]
Example syntax from https://github.com/projectdiscovery/httpx/issues/946:

```console
   -up, -update                 update project to the latest released version
   -duc, -disable-update-check  disable automatic update check
```

The option should just notify the user of a new version availability and no update should happen automatically.

Note: the library aims to be generic, so the self-update mechanism should be abstracted enough to accept a custom endpoint, support semantic versioning and it should be optional

Ref:
- Discussed with @tarunKoyalwar 
- https://github.com/projectdiscovery/team-backlogs/issues/243
- https://github.com/projectdiscovery/httpx/issues/946
- https://github.com/projectdiscovery/nuclei/issues/3285

**Comment by tarunKoyalwar** [comment]
@Mzack9999 ,since directly importing `pdtm` won't be possible (cyclic import) . How about we add a callback options instead and let developer manage it and Create a helper function that returns a callback options in `pdtm`. 


```go
flagSet.AddUpdateGroup(toolName string, UpdateCheckCallback func, UpdateCallback func)
```


## In pdtm 
we add public function that returns above callbacks
```go
func GetUpdateCheckCallback(toolName ,toolVersion string)  func() { xxx }
```

```go
func GetUpdateCallback(toolName string) func()  {}
```

**Comment by tarunKoyalwar** [comment]
and we can also add other options to this `UpdateGroup` with their respective callback functions . Ex: `nuclei-templates` and `fuzzing templates`

**Comment by Mzack9999** [comment]
@tarunKoyalwar that's a valid point. I believe that a good part of the pdtm logic (eg. paths, CRUD in files) are generic and reusable enough to be moved into utils, probably at the point that pdtm doesn't even need a runner folder, but just use the same callbacks mechanism of goflags (let's remember that also pdtm is another tool of the potential update list, likely without delete/install overridden callbacks).
I second the the proposal of a generic update group, which will allow handling uniformely templates of various type.
