### ISSUE TITLE
How can I avoid filtering double quotes?

### ISSUE THREAD

**Issue by zan8in** [projectdiscovery/goflags#146]
code:
```
flagSet.StringVarP(&options.Search, "search", "s", "", "query conditions"),
```
cmd:
`-s domain="example.com"`

The output result of golang debug is 
`domain=example.com`

**How can I avoid filtering double quotes?**

**Comment by Mzack9999** [comment]
Unfortunately this is a side effect of forceful values normalization introduced back then to handle particular comma separated values, which is going to be removed as it's a go anti-pattern, I'm opening a follow up issue. For the time being you can try with escaping `\"`
