### ISSUE TITLE
`DynamicVar` did unexpected works

### ISSUE THREAD

**Issue by XiaoliChan** [projectdiscovery/goflags#187]
`DynamicVar` & `DynamicVarP` is not working

ENV:
- Go 1.20.14
- goflags v0.1.54

Code:
https://github.com/projectdiscovery/goflags/blob/main/examples/basic/main.go

Issues details:
- Always get the value `0` even if it set default value to `50` in `int` type data (string will get blank value)

**Comment by XiaoliChan** [comment]
@RamanaReddy0M I see, but it looks like weird
```
┌──(xiaoli㉿kali)-[/tmp/goflags/examples/basic]
└─$ ./main 
Got Severity: [high]
Dynamic Values Output
title size: 0
target: 
hashes: []
                                                                                                                      
┌──(xiaoli㉿kali)-[/tmp/goflags/examples/basic]
└─$ ./main -title
Got Severity: [high]
Dynamic Values Output
title size: 50
target: 
hashes: []
```

In the user's eyes, it should look like other flags, provide a default value to the variable.

The second thing is even I provide value to the flag, it looks like a `bool` type variable.
```                                                                                                                      
┌──(xiaoli㉿kali)-[/tmp/goflags/examples/basic]
└─$ ./main -title 10
Got Severity: [high]
Dynamic Values Output
title size: 50
target: 
hashes: []
```

**Comment by RamanaReddy0M** [comment]
@XiaoliChan 
```console
$ ./main -title=10
```
This is how you are supposed to pass the value for the flags created by **DynamicVar**.

The **DynamicVar** serves the purpose of flag without value(takes default value) or with value which is missing in go standard library and `flag=xxx` is the limitation we had here.

If this is not the case you can use regular **IntVar** for the consistency.

**Comment by XiaoliChan** [comment]
@RamanaReddy0M Thanks for providing more details about `DynamicVar`

The reason why I asking this, because I want to use `float` type value, but looks like it's not support

**Comment by RamanaReddy0M** [comment]
```go
var tmp float64
flagSet.CreateGroup("Dynmaic", "Dynamic",
		flagSet.DynamicVar(&tmp,  "tmp", 38.0, "temperature"),
	)
```
it support float as well.

**Comment by XiaoliChan** [comment]
Oh, I also need to set it as default XD

**Comment by RamanaReddy0M** [comment]
@XiaoliChan seems resolved closing the issue.
