### ISSUE TITLE
goflags doesn't create a valid default slice for StringSliceVar in config file with `Marshal` set as true

### ISSUE THREAD

**Issue by parrasajad** [projectdiscovery/goflags#21]
Example: 
  In notify we have  `StringSliceVar` flag `provider`  with default value as `[]string{}`, generated config file has the provider value as: `provider: '[]'`

**Comment by forgedhallpass** [comment]
For bugs please put the "bug" label, describe the steps to reproduce, the current result and the expected one.
I assume you are expecting `provider: []` without the single quotes?

**Comment by parrasajad** [comment]
@forgedhallpass, you assumed it right. Steps to reproduce: Use `StringSliceVar` (or `NormalizedStringSliceVar`) with `Marshal` set as `true`.
